-- Deprecated legacy schema file.
-- Do not use this for commercial deployment.
-- Use: supabase/gamertabs-commercial-schema.sql
-- It includes subscription ownership, game_saves, secure profile policies,
-- room/friend/message RLS, and the helper RPC functions required by GamerTabs.
